SELECT 
    r.FOOD_TYPE,
    r.REST_ID,
    r.REST_NAME,
    r.FAVORITES
FROM REST_INFO r
WHERE r.FAVORITES = (
    SELECT MAX(r2.FAVORITES)
    FROM REST_INFO r2
    WHERE r2.FOOD_TYPE = r.FOOD_TYPE
)
ORDER BY r.FOOD_TYPE DESC;