WITH base AS (
  SELECT USER_ID
  FROM USER_INFO
  WHERE YEAR(JOINED) = 2021
),
sales AS (
  SELECT YEAR(SALES_DATE) AS YEAR,
         MONTH(SALES_DATE) AS MONTH,
         COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS
  FROM ONLINE_SALE s
  JOIN base b ON s.USER_ID = b.USER_ID
  GROUP BY YEAR, MONTH
)
SELECT 
  s.YEAR,
  s.MONTH,
  s.PURCHASED_USERS,
  ROUND(s.PURCHASED_USERS / (SELECT COUNT(*) FROM base), 1) AS PURCHASED_RATIO
FROM sales s
ORDER BY s.YEAR, s.MONTH;
