SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS july_sum
    FROM JULY
    GROUP BY FLAVOR
) j ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.july_sum) DESC
LIMIT 3;