WITH RECURSIVE hours AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM hours WHERE HOUR < 23
),
cnt AS (
  SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS cnt
  FROM ANIMAL_OUTS
  GROUP BY HOUR(DATETIME)
)
SELECT h.HOUR,
       COALESCE(c.cnt, 0) AS COUNT
FROM hours h
LEFT JOIN cnt c USING (HOUR)
ORDER BY h.HOUR;